name: pharm_rx
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  retrofit: '>=3.0.0 <4.0.0'
  dio: ^4.0.6
  logger: any
  vector_math: ^2.1.2
  get_it: ^7.2.0
  auto_route: ^5.0.1
  azlistview: ^2.0.0
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^1.0.4
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  retrofit_generator: '>=4.0.0 <5.0.0'
  auto_route_generator: ^5.0.1

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/
